---
title: "git_01"
author: "Alyssa Gutierrez"
date: "5/28/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
I have a fairy by my side  
Which says I must not sleep  
When once in pain I loudly cried  
It said you must not weep  
If full of mirth I smile and grin  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow road  
And sorry I could not travel both  
And be on traveler long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth   

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea  
Shining with all his might  
He did his very best to make   
The billows smooth and bright   
And this was odd because it was  
The middle of the night   

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

ChatGPT
In a haze of green, I softly float,   
Where time dissolves, and worries demote.   
Eyes glazed over, mind takes flight,   
In the realm of dreams, I find delight.   

Senses alive, colors dance and sing,   
Every giggle, a bell's sweet ring.   
Munchies beckon, flavors divine,   
Journeying through tastes, a feast in line.   

Gravity’s grip, a gentle caress,   
Weightless whispers, in a state of bless.   
Thoughts unravel, in a cosmic stream,   
Lost in the stars, in a mind's dream.   

Giggles erupt, laughter takes flight,   
In this euphoria, everything's bright.   
Time stretches out, in a slow parade,   
Moments linger, in a serenade.   

Reality bends, in a gentle sway,   
In this altered state, I blissfully stay.   
Weed's embrace, a tranquil sea,   
In its gentle waves, I am free.   